### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)`

### ISSUE THREAD

**Issue by AlgebraFalcon** [lucidrains/big-sleep#50]
I found an error
`RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasGemmEx( handle, opa, opb, m, n, k, &falpha, a, CUDA_R_16F, lda, b, CUDA_R_16F, ldb, &fbeta, c, CUDA_R_16F, ldc, CUDA_R_32F, CUBLAS_GEMM_DFALT_TENSOR_OP)``
when attempting to call the run the sample code provided in the ReadMe,:
`from big_sleep import Imagine

dream = Imagine(
    text = "fire in the sky",
    lr = 5e-2,
    save_every = 50,
    save_progress = True
)

dream()`

The error seems to have occurred here:
`File "D:\Anaconda\lib\site-packages\torch\nn\functional.py", line 1753, in linear
    return torch._C._nn.linear(input, weight, bias)`

Does anyone know why this would occur? I am running my code on a 64 bit Windows 10 laptop with a GeForce GTX 1660 Ti Graphics Card

**Comment by apprehensivetarget** [comment]
I am gettind the same error.

**Comment by TheGildedGoo** [comment]
Having the same error utilizing a 1660 Super. Thinking it may have something to do with the GPU.

**Comment by apprehensivetarget** [comment]
I fixed it by reinstalling pytotch

**Comment by Rerumu** [comment]
Having this issue on Debian with my GTX 1660 Super. Reinstalling pytorch did not help.

**Comment by anvarganiev** [comment]
I had wrong tensor shape in NN architecture. In one place there was 32x0x6 tensor.

**Comment by 0xBYTESHIFT** [comment]
Got this issue too, using the default CLI, not a .py file with my parameters. How to fix it?
